package SWING;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class Product_Frm extends javax.swing.JFrame {
Connection cn=null;
Statement st=null;
ResultSet rs=null;
PreparedStatement ps=null;
String insert_sql="insert into product values(?,?,?,?,?)";
String delete_sql="delete from product where pid=?";
String update_sql="update product set pname=? , price=? ,color=? , model=? where pid=?";
String select_sql="select * from product order by pid";
    /**
     * Creates new form Product_Frm
     */
    public Product_Frm() {
        initComponents();
    }
public void insertData()
  {
      try
      {
          ConnectionFactory con=new ConnectionFactory();
          cn=con.getConn();
          ps=cn.prepareStatement(insert_sql);
          ps.setString(1,pid_txt.getText());
          ps.setString(2,pname_txt.getText());
          ps.setString(3, price_txt.getText());
          ps.setString(4, color_combo.getSelectedItem().toString());
          ps.setString(5,model_txt.getText());
          ps.executeUpdate(); 
          cn.commit();
      }
      catch(SQLException se)
      {
          se.printStackTrace();
      }
      
  }
public void getData()
  {
      try
      {
          ConnectionFactory con=new ConnectionFactory();
          cn=con.getConn();
          st=cn.createStatement();
          rs=st.executeQuery(select_sql);
          product_table.setModel(DbUtils.resultSetToTableModel(rs));
          
      }
      catch(SQLException se)
      {
          se.printStackTrace();
      }
      
  }
public void deleteData()
  {
      try
      {
          ConnectionFactory con=new ConnectionFactory();
          cn=con.getConn();
          ps=cn.prepareStatement(delete_sql);
          ps.setString(1,pid_txt.getText());
          ps.executeUpdate();
          cn.commit();
      }
      catch(SQLException se)
      {
          se.printStackTrace();
      }
      
  }
public void updateData()
  {
      try
      {
          ConnectionFactory con=new ConnectionFactory();
          cn=con.getConn();
          ps=cn.prepareStatement(update_sql);
          ps.setString(1,pname_txt.getText());
          ps.setString(2,price_txt.getText());
          ps.setString(3,color_combo.getSelectedItem().toString());
          ps.setString(4,model_txt.getText());
          ps.setString(5,pid_txt.getText());
          ps.executeUpdate();
          cn.commit();
      }
      catch(SQLException se)
      {
          se.printStackTrace();
      }
      
  }
public void refreshData()
  {
      pid_txt.setText("");
      pname_txt.setText("");
      price_txt.setText("");
      model_txt.setText("");
  }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pid_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pname_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        price_txt = new javax.swing.JTextField();
        color_combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        model_txt = new javax.swing.JTextField();
        save_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        show_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" ADD  PRODUCT");

        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(product_table);

        jLabel1.setText("PRODUCT ID");

        jLabel2.setText("PRODUCT NAME");

        jLabel3.setText("PRICE");

        color_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "red", "blue", "green", "black" }));
        color_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_comboActionPerformed(evt);
            }
        });

        jLabel4.setText("COLOR");

        jLabel5.setText("MODEL");

        save_button.setText("SAVE");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        update_button.setText("UPDATE");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        delete_button.setText("DELETE");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        close_button.setText("CLOSE");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        show_button.setText("SHOW");
        show_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_buttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("ADD PRODUCT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(update_button)
                                .addGap(30, 30, 30)
                                .addComponent(delete_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(close_button))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(model_txt)
                                    .addComponent(color_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pid_txt)
                                    .addComponent(pname_txt)
                                    .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(269, 269, 269)
                                        .addComponent(show_button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(color_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(model_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(show_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close_button)
                    .addComponent(delete_button)
                    .addComponent(update_button)
                    .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1041, 599);
    }// </editor-fold>//GEN-END:initComponents

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        // TODO add your handling code here:
         if(pid_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"PRODUCT ID IS EMPTY");
        }
        else if(pname_txt.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(this,"PRODUCT NAME IS EMPTY");
        }
        else if(price_txt.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(this,"PRICE IS EMPTY");
        }
        
        else if(model_txt.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(this,"MODEL IS EMPTY");
        }
        else
        {
        this.insertData();
        this.refreshData();
        JOptionPane.showMessageDialog(this,"DATA INSERTED SUCCESSFULLY");
        this.getData();
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        
         if(pid_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"PRODUCT ID IS EMPTY");
        }
        else if(pname_txt.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(this,"PRODUCT NAME IS EMPTY");
        }
        else if(price_txt.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(this,"PRICE IS EMPTY");
        }
        
        else if(model_txt.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(this,"MODEL IS EMPTY");
        }
        else
        {
        this.updateData();
        this.refreshData();
        JOptionPane.showMessageDialog(this,"DATA UPDATED SUCCESSFULLY");
        this.getData();
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        if(pid_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"PRODUCT ID IS EMPTY");
        }
     
        else
        {
        this.deleteData();
        this.refreshData();
        JOptionPane.showMessageDialog(this,"DATA DELETED SUCCESSFULLY");
        this.getData();
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_buttonActionPerformed

    private void show_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_buttonActionPerformed
        // TODO add your handling code here:
        this.getData();
    }//GEN-LAST:event_show_buttonActionPerformed

    private void color_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_color_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_Frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_button;
    private javax.swing.JComboBox<String> color_combo;
    private javax.swing.JButton delete_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField model_txt;
    private javax.swing.JTextField pid_txt;
    private javax.swing.JTextField pname_txt;
    private javax.swing.JTextField price_txt;
    private javax.swing.JTable product_table;
    private javax.swing.JButton save_button;
    private javax.swing.JButton show_button;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
